### PR TITLE
Fixes issue #49

### PR DESCRIPTION
**Pull request by alecgarza96**
Fixes issue #49

### CODE REVIEW

**Comment by alecgarza96** [comment]
added .s file extension for assembly support

**Comment by polac24** [comment]
Are you sure this fixes #49? The original problem was reported for `CNIOBoringSSL` library, which uses `*.S` (not `*.s`) files (e.g. https://github.com/apple/swift-nio-ssl/blob/main/Sources/CNIOBoringSSL/crypto/fipsmodule/aesni-gcm-x86_64.linux.x86_64.S). 
`isSuffixed` is case sensitive so it wouldn't consider `aesni-gcm-x86_64.linux.x86_64.S` as a valid input file.

**Comment by alecgarza96** [comment]
I committed the changes to this PR and they appear to be reflected when I verify in the Files Changed section. Let me know if this works, or if a new PR should be opened. New to this repo

**Comment by alecgarza96** [comment]
image
getting following error as reason for failed tests, troubleshooting

**Review by polac24 — APPROVED** [review]

**Comment by polac24** [comment]
That seem to be a reason of a non-stable test setup. I tried to stabilize it in #81, but still without success.

**Pull request merged**
