### PR TITLE
Support exposing enums from ObjC via Bridging headers

### PR DESCRIPTION
**Pull request by polac24**
Part III (out of IV) of #140 fix

* an artifact .zip for a swift target, stores two ObjC headers: `-Swift.h` and `-Swift.h.md5`. Because the former could contain absolute paths, the latter file is used in a dependency fingerprint (just like `.swiftmodule` files) - its content is just the same as the .swiftmodule's override (a fingerprint of the target)
* Producer and consumers for each `.h` dependency, check if an override is available. If so, its content is used for the fingerprint
* Because `-Swift.h.md5` is automatically placed next to the `-Swift.h` only for a .framework, a developer that wants to cover that for a static library, has to manually add an extra `ditto` (similar to `cp`) build step to move `-Swift.h.md5` along `-Swift.h`. Required steps are documented in Readme.md. _This scenario can be considered (only static library + exposing enum via a bridging header) as an edge case - very unlikely to happen._

This part unblocks `rake e2e:run_standalone` added in #147.

### CODE REVIEW

**Review by PatrikBillgren — DISMISSED** [review]
Looks really good! Approved, I just noticed one minor nit in a comment

**Comment by polac24** [comment]
@PatrikBillgren, can you please reapprove after my typo fix?

**Review by CognitiveDisson — APPROVED** [review]

**Comment by CognitiveDisson** [comment]
@polac24 Should we merge it?

**Comment by polac24** [comment]
@CognitiveDisson, yes. let me merge it.

**Pull request merged**
